Update blacklist.py
msg is not a member of IOError; so this "raise MissingConfigError" raises: AttributeError: 'exceptions.IOError' object has no attribute 'msg'

I think you meant e.message, but that has no string output, so what you really want (I believe) is str(e).